name: Setup
description: Set up Node and dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: npm
    - uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: d6de5cbdc8-${{ hashFiles('**/package-lock.json') }}
        restore-keys: d6de5cbdc8-
    - name: Install dependencies
      run: npm ci --prefer-offline
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        SKIP_COMPILE: true
