dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "6"
before_install:
  - npm install truffle@3.2.2 -g
  - npm i -g ethereumjs-testrpc
before_script:
  - rbenv global 2.3.1 && gem install danger --version '~> 4.0' && danger
script:
  - testrpc > /dev/null &
  - truffle test
after_script:
  - npm run coveralls
