[profile.default]
solc_version = '0.8.24'
evm_version = 'cancun'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./test/utils/cryptography/wycheproof.jsonl" }]

[fuzz]
runs = 5000
max_test_rejects = 150000
