version: 2

orbs:
  slack: circleci/slack@3.2.0

jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -p 8545  # for networks['development'] in `truffle-config.js`
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -p 8555  # for networks['coverage'] in `truffle-config.js`
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install npm wee
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Linter
          command: npm run lint
      - run:
          name: Unit tests
          command: npm run test
      - run:
          name: Unit tests with coverage report
          command: npm run test
          environment:
            SOLIDITY_COVERAGE: true

      # TODO(xinbenlv, #1839): run SOLC_NIGHTLY to be run but allow it to fail.
      # TODO(xinbenlv, #1839): requires SLACK WEBHOOK to be setup by repo owner
      - slack/status:
          fail_only: true # Optional: if set to `true` then only failure messages will occur.
          only_for_branch: "master" # Optional: If set, a specific branch for which status updates will be sent. In this case, only for pushes to master branch.

