name: lint workflows

on:
  pull_request:
    paths:
      - '.github/**/*.ya?ml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add problem matchers
        run: |
          # https://github.com/rhysd/actionlint/blob/3a2f2c7/docs/usage.md#problem-matchers
          echo "::add-matcher::.github/actionlint-matcher.json"
      - uses: docker://rhysd/actionlint:latest
