name: transpile upgradeable

on:
  push:
    branches:
      - master
      - release-v*

jobs:
  transpile:
    environment: push-upgradeable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          repository: OpenZeppelin/openzeppelin-contracts-upgradeable
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
      - name: Fetch current non-upgradeable branch
        run: |
          git fetch "https://github.com/${{ github.repository }}.git" "$REF"
          git checkout FETCH_HEAD
        env:
          REF: ${{ github.ref }}
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Transpile to upgradeable
        run: bash scripts/upgradeable/transpile-onto.sh ${{ github.ref_name }} origin/${{ github.ref_name }}
      - run: git push origin ${{ github.ref_name }}
